### ISSUE TITLE
Unable to Update Article Content

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#14]
After I press the submit button to edit my article, I get this error.

Error: When assigning attributes, you must pass a hash as an argument.

I set the variable article equal to the particular hash for an article based on ID and it follows the same format I used in the fruit farm assignment to edit a farm.

https://github.com/anastasiaalt/PatzoParty/blob/master/views/article.erb
https://github.com/anastasiaalt/PatzoParty/blob/master/server.rb

```
  put "/articles/:id/edit" do
    article = Article.find(params[:id])
    article.update(params[:article])
    redirect to "/articles"
  end
```

**Comment by phlco** [comment]
You need to look at your views. The params hash is structured based on the name values in the input elements in your html.

The only reason you could pass params[:crop] and have it work is because how the name attributes were set up in your HTML. 

See here: 

```
 <input type="text" name="crop[color]" placeholder="color">
```

This creates a hash "crop" with a key "color" so that you can do params[:crop]

You'll need to format your article the same way if you want to use that syntax.
