### ISSUE TITLE
Username / Two Names for Log In?

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#7]
Encountering and issue with the login for editors and authors. The issue stems from the fact that I designed my Author and Editor schema to have two names: name1 or first name and name2 or last name. The username field for a single name (such as name1) was not allowing for login so i made it into a two part first and last name matched to a single password.... It's revealing the fact that I don't follow how in the form you designate something is 1) the username associated with a password and 2) how you map or correspond or add that username to the table for authors or editors...

  <div><input type="text" name="name1" placeholder="First Name"></div>
  <div><input type="text" name="name2" placeholder="Last Name"></div>
  <div><input type="password" name="password" placeholder="password"></div>
  <div><input type="password" name="password_confirmation" placeholder="password confirmation"></div>

**Comment by phlco** [comment]
This brings up some interesting points. 

First, naming.  Since you have to explain to me "name1 or first name and name2 or last name" it may make more sense to use `first_name` and `last_name` as your column names. That makes more semantic sense. 

Second, "I don't follow how in the form you designate something is the username associated with a password"

There is no designation. They're just input fields and a user enters data into them. It's our job as developers to group them in some sort of meaningful way.  When you create an input field you need to designate the "name" attribute. This will be the key to the value sent over in params.

Keys should be unique.  Here's where I see a problem: 

```
  <input type="text" name="name" placeholder="First Name">
  <input type="text" name="name" placeholder="Last Name">
```

Third, once you've passed data back to your server via the form submission, the values are available inside of params. It's up to you as the developer to then deliver that data into your tables by using ActiveRecord.

**Comment by anastasiaalt** [comment]
Awesome! I have this working now. Thank you for great explain.
