### ISSUE TITLE
Login for Authors / Editors

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/PatzoParty#9]
I have structured my login such that I have one for Editors and one for Authors with different viewing abilities. The erb files for logging in as an Author or an Editor are identical however. Both post to sessions but the routing in the server file creates an instance of author rather than editor and vice versa in both cases. I am finding when I create a new Editor and then go to log in as that editor, after I press the login button on the page that correctly renders the login_editor.erb, the log in is not successful and I am routed to the login_author. I have been troubleshooting and thinking about why that is going back to my index page. I have the logic as checking for Author, then Editor, then directing to Log In if neither... I can't follow how it does not recognize the Editor I created and the session I started with that editor unless it is somehow confused around session keys with the two different types of users, editors and authors... Any insights on session keys to help me further resolve from here?

**Comment by phlco** [comment]
You have the following in your `server.rb`

```
  post "/sessions" do
    # author stuff
  end  

  post "/sessions" do
     # editor stuff
  end  
```

You can't have two route handlers for posting to the same path. Sinatra will only execute the first one. 

You're going to need to create a different route handler (which means different paths) for each or include more information in your form so that you can do some conditional logic based on the data you send over in params to login either an author or editor.
